### ISSUE TITLE
MDL-41244 Atto HTML Editor - Table support

### ISSUE THREAD

**Issue by damyon** [damyon/moodle-editor_atto#11]

**Comment by DBezemer** [comment]
This is currently the only reason why I would not use Atto.
Whenever creating non-flat content tables are crucial.

What would be even more awesome is support for div's and span's instead of tables to achieve the same goal, but full HTML5 compliant. If there is anything I can do to help with this, feel free to contact me.

**Comment by DBezemer** [comment]
maybe this is of some help: https://github.com/bgkittrell/yui-rte-tables

**Comment by damyon** [comment]
Thanks very much for the suggestion - it's a good one. 

Agree tables are very important (as long as it's for tabular data). A table plugin IMO would have to not only create tables - but ensure that the tables contain the required markup for screen readers.

Re: HTML5 - DL/DD lists are also good - (but can be hard to style nicely). Also some more general "float left, float right" options for layout would be useful.

In general my plan is to have lots of these extra plugins available for Atto - but not included by default. This way the default installation is the bare minimum (about what we have now) and admins can choose to install the extra ones (so they can keep the number of buttons in their toolbar sane). 

If you are willing to help work on this it would be great - some of the code in that yui tables plugin would be useful (even if it's just to validate the UI). The bundled plugins are good examples of how to add plugins to Atto, and I'll work on documenting this nicely in the next few weeks.

**Comment by damyon** [comment]
Released an update with table support last week.
