### ISSUE TITLE
Bump version number for Moodle 2.5 branch

### ISSUE THREAD

**Issue by DBezemer** [damyon/moodle-editor_atto#15]
Currently the plugins and editor wont update as the "old" or testing version that is installed has a lower version number than your github version.
My suggestion would be to bump it to 20131027 or 20131028 to resolve this

**Comment by damyon** [comment]
Thanks - this is deliberate - there are separate versions for 2.5 and 2.6 - so if you install the 2.5 version, then upgrade to Moodle 2.6 you will see there is an update available. 

They have identical features - just some of the plugin code underneath requires changes for each version.

**Comment by DBezemer** [comment]
alright, I experienced the proble because I backported your 2.6 branch myself and did not downbump the version number. Was going to file a pull request, but then you already backported it yourself.

Ill see if I can get some work done on the table/div/span editor anytime soon

**Comment by damyon** [comment]
np - I see the table editor as more of an accessible grid editor (re: http://www.w3.org/WAI/PF/aria/#grid) - I doubt I would get a chance to look at this properly before the 2.6 release - so in the meantime you are more than welcome to have a go. If you have any questions - feel free to ask.
